### ISSUE TITLE
computeBinStats

### ISSUE THREAD

**Issue by jeremygam** [jonesr18/MATLAB_Flow_Analysis#9]
'bins' does not default to 'all'
help says '50th' rather than p50 for median

**Comment by jeremygam** [comment]
Another issue?

binned_data = dataSamples.computeBinStats(1,struct('channels',{'FITC_A','Alexa_Fluor_700_A','PE_A'},'bins','all'),'p50');

Error using ischar
Too many input arguments.

Error in FlowData/computeBinStats/checkInputs_computeBinStats (line 967)
				if (isfield(sliceParams, 'channels') && ischar(sliceParams.channels))

Error in FlowData/computeBinStats (line 915)
			checkInputs_computeBinStats(self);

**Comment by jeremygam** [comment]
would be more intuitive to have computeBinStats output stats in the same dimension. Eg. if you are binning in two dimensions with 10 bins each, output would be separate 10x10 for each channel (C). Right now it is a BxC matrix where B is all bins concatenated into a single column

**Comment by jonesr18** [comment]
I've decided to not structure the bins stats into their "true" shape since this would require always requesting bins from an entire row/column to avoid errors in the matrix reshaping process. Additionally, it would require quite a bit of deconvoluting the requested bins and ultimately it is easier to just have the user reshape their own data.

Maybe in the future we can add an option for requesting 'binRows' and 'binCols' and 'bin3Ds' and such for asking for all bins in a particular _i_th dimensional index? Then structuring the output would be easier and guaranteed to not crash on reshape()

**Comment by jeremygam** [comment]
hmmm whatever you decide to do, it will be helpful to put this info in the
help

**Comment by jonesr18** [comment]
For the record - it was changed so that if you request all bins, the output is N+1 dimensional - the first N dimensions are the bin dimensions and the last are the channels. If specific bins are requested, then the output is 2D with the first dimension being the bins in the order requested the and second dim being the channels.
